trigger: none
resources:
  pipelines:
  - pipeline: build
    source: 'dontnet - Build' 
stages:
- stage: DeployDev
  displayName: 'Deploy to DEV'
  jobs:
  - template: azure-pipelines-cd-template.yml
    parameters:
      azureSubscription: '<YOUR-AZURE-SUBSCRIPTION-SERVICE-CONNECTION>'
      appName: '<YOUR-BACKEND-DEV-APP-SERVICE-NAME>'
      artifactName: 'App'
      packagePath: '$(Pipeline.Workspace)/App'  # From .NET build pipeline artifact
      appSettings: |
        ASPNETCORE_ENVIRONMENT=Development
        ConnectionStrings__DefaultConnection=<DEV-CONNECTION-STRING>
      environment: 'dev'

- stage: DeployQA
  displayName: 'Deploy to QA'
  jobs:
  - template: azure-pipelines-cd-template.yml
    parameters:
      azureSubscription: '<YOUR-AZURE-SUBSCRIPTION-SERVICE-CONNECTION>'
      appName: '<YOUR-BACKEND-QA-APP-SERVICE-NAME>'
      artifactName: 'App'
      packagePath: '$(Pipeline.Workspace)/App'  # From .NET build pipeline artifact
      appSettings: |
        ASPNETCORE_ENVIRONMENT=QA
        ConnectionStrings__DefaultConnection=<QA-CONNECTION-STRING>
      environment: 'qa'

- stage: DeployStg
  displayName: 'Deploy to STG'
  jobs:
  - template: azure-pipelines-cd-template.yml
    parameters:
      azureSubscription: '<YOUR-AZURE-SUBSCRIPTION-SERVICE-CONNECTION>'
      appName: '<YOUR-BACKEND-STG-APP-SERVICE-NAME>'
      artifactName: 'App'
      packagePath: '$(Pipeline.Workspace)/App'  # From .NET build pipeline artifact
      appSettings: |
        ASPNETCORE_ENVIRONMENT=Staging
        ConnectionStrings__DefaultConnection=<STG-CONNECTION-STRING>
      environment: 'stg'

- stage: DeployProd
  displayName: 'Deploy to PROD'
  jobs:
  - template: azure-pipelines-cd-template.yml
    parameters:
      azureSubscription: '<YOUR-AZURE-SUBSCRIPTION-SERVICE-CONNECTION>'
      appName: '<YOUR-BACKEND-PROD-APP-SERVICE-NAME>'
      artifactName: 'App'
      packagePath: '$(Pipeline.Workspace)/App'  # From .NET build pipeline artifact
      appSettings: |
        ASPNETCORE_ENVIRONMENT=Production
        ConnectionStrings__DefaultConnection=<PROD-CONNECTION-STRING>
      environment: 'prod'