trigger:
  branches:
    include:
      - main

variables:
  azureSubscription: 'Your-Service-Connection-Name'
  appName: 'blog-app-service'
  resourceGroup: 'blog-app-rg'

stages:
- stage: Build
  jobs:
  - job: BuildApp
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
      displayName: 'Install Node.js'

    - script: |
        cd frontend
        npm install
        npm run build
      displayName: 'Build Frontend'

    - script: |
        cd backend
        npm install
        npm run build
      displayName: 'Build Backend'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(System.DefaultWorkingDirectory)'
        artifactName: 'drop'

- stage: Deploy
  dependsOn: Build
  jobs:
  - deployment: DeployApp
    environment: 'production'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: $(azureSubscription)
              appType: webApp
              appName: $(appName)
              package: '$(Pipeline.Workspace)/drop/frontend'
